# Generated by Django 5.2.8 on 2025-12-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='full_text',
            new_name='article',
        ),
    ]
